name: Pull Request Assigned

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]


jobs:
  handle-assigned:
    runs-on: ubuntu-latest
    steps:
      - name: Check if pull request is linked to an issue
        id: get-linked-issue
        run: |
          echo "ISSUE_NUMBER=$(jq -r '.issue.number' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          
      - name: Check if pull request is linked to an issue
        id: get-linked-issue
        run: echo "::set-output name=issue_number::$(jq -r '.issue_url' $GITHUB_EVENT_PATH | cut -d'/' -f7)"

      - name: Log issue and pull request information
        run: |
          echo "Issue Title: ${{ github.event.pull_request.title }}"
          echo "Issue Number: ${{ github.event.pull_request.number }}"
          echo "Assignee: ${{ github.event.assignee.login }}"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Project Card Action
        uses: ineshbose/project-card-action@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.pull_request.id }}
          TARGET_COLUMN: 👀 In review
